### PR TITLE
remove isActive

### PR DESCRIPTION
**Pull request by kristojorg**
This PR removes references to the unused `isActive` property in `opds-web-client`'s `router` context. This is the corresponding PR in OWC: https://github.com/NYPL-Simplified/opds-web-client/pull/259

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
This didn't even need an update to the new OWC 0.4.1 version (now published) but I think it'll be good to update that package to keep things up-to-date.

**Comment by kristojorg** [comment]
Yea it was only used it tests. Will update to that one here

**Comment by kristojorg** [comment]
Ok I've updated the `opds-web-client` package, so y'all can merge this when ready

**Comment by EdwinGuzman** [comment]
Ah, I didn't know you had access to merge in this repo. I approved it so that @adriana-alter could do the merge since she has an upcoming update as well. This hasn't been released on npm so it's not a big deal.

**Comment by kristojorg** [comment]
Ah okay sorry, I figured you had given me merge access for this reason. I'll defer merging to you all from now on

**Comment by EdwinGuzman** [comment]
Not a problem. It's fine if you can do it for the opds-web-client, but for this repo Adriana is actively working on it.

**Pull request merged**
