### PR TITLE
replaced inherited getMedium w imported version

### PR DESCRIPTION
**Pull request by kristojorg**
Ok @EdwinGuzman this PR maps to https://github.com/NYPL-Simplified/opds-web-client/pull/258 and replaces inherited `this.getMedium` and `this.getMediumSVG` with the imported versions. 

This is a draft PR because it _does not_ update the `opds-web-client` package, which will be necessary to make this work. Once the PR in `opds-web-client` is published to npm, we can update the package in this PR and merge it.

### CODE REVIEW

**Comment by kristojorg** [comment]
FYI These tests are failing because it can't find the new `opds-web-client/lib/utils/book` module. Should resolve with the new `opds-web-client` version.

**Comment by EdwinGuzman** [comment]
Cool, thanks. This mostly works but I do get these two errors locally:

```
src/components/BookEditForm.tsx:81:35 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'BookData'.

81     const mediumValue = getMedium(this.props.medium);
                                     ~~~~~~~~~~~~~~~~~

src/components/CatalogPage.tsx:57:10 - error TS2739: Type '{ children: Element; }' is missing the following properties from type '{ children: ReactNode; actions: ActionCreator; fetcher: DataFetcher; }': actions, fetcher

57         <ActionsProvider>
```

Other than that, the changes look fine. When you do bump up the version in package.json later, also update the changelog and the version for this repo, too.

**Comment by kristojorg** [comment]
Ah yes, that's because I made a `BookMedium` enum type that specified the possible values, so a string won't work. I'll fix that in this repo to be more specifically typed.

**Comment by EdwinGuzman** [comment]
`opds-web-client` v0.4.0 is now released and ready to use here.

**Comment by kristojorg** [comment]
Ok I updated `opds-web-client` and fixed the errors. This should be ready so long as tests pass in CI

**Comment by EdwinGuzman** [comment]
Looks good to me but adding @adriana-alter to also review.

**Comment by kristojorg** [comment]
Shall I merge this then?

**Comment by EdwinGuzman** [comment]
Do you have the ability to merge? I'll do it and push it to npm for now.

**Pull request merged**
