### PR TITLE
Cdn success

### PR DESCRIPTION
**Pull request by adriana-alter**
Resolves https://jira.nypl.org/browse/SIMPLY-1400.  The success message wasn't showing up on creating/editing a CDN service (and once I got it showing up I realized that my capitalization check needed changes).

### CODE REVIEW

**Comment by adriana-alter** [comment]
This does not seem to merit its own version number; ok to tack it onto 0.0.85?

**Comment by aslagle** [comment]
It's fine to add it on to 0.0.85 if it hasn't been published to npm yet, otherwise you can't update it and need a new version.

**Comment by adriana-alter** [comment]
0.0.85 has not been published yet; I'll add this!

**Comment by aslagle** [comment]
you should also publish once you merge this - in general you want whatever circulation is pointing to to be published, so the docker image from master will work and any developers who aren't working on the front-end can get it.

**Pull request merged**
