### PR TITLE
Add preview button instead of trying to preview when input changes

### PR DESCRIPTION
**Pull request by adriana-alter**
Resolves https://jira.nypl.org/browse/SIMPLY-2021

### CODE REVIEW

**Comment by aslagle** [comment]
It seems pretty unlikely to me that anyone would type a URL letter by letter - this was meant for copy and paste.

**Comment by EdwinGuzman** [comment]
That's true, but it's still a usability issue.

**Comment by adriana-alter** [comment]
I agree that this is a very unlikely use case...but just on principle, I'd rather not use that as justification for implementing a pattern that (I'm pretty sure) violates accessibility guidelines...

**Comment by aslagle** [comment]
It seems like it should be possible to fix the accessibility issue without slowing down the main use case - though I didn't look at the code, so maybe you did that :)

This is kind of a niche feature that's mainly for open bookshelf, so not a huge deal anyway.

**Comment by aslagle** [comment]
Yeah that doesn't sound too bad.

**Comment by EdwinGuzman** [comment]
The code looks fine but it's not working for me. Whenever I click on the "preview" button the page refreshes (I'm not sure if you intended to change this as well) which is fine but nothing happens. No error messages or successful preview shows up (I'm on the latest for everything) after clicking on "preview".

Expected result (from QA server):
1 - error
Screen Shot 2019-06-03 at 12 44 05 PM
2 - successful
Screen Shot 2019-06-03 at 12 45 33 PM

**Comment by adriana-alter** [comment]
I figured it just didn't work in local; it doesn't work for me in local on `master`.  Does it for you??  (Fixing the page refresh thing meanwhile, though!)

**Comment by EdwinGuzman** [comment]
This works for me on local on `master`. This includes displaying the error message and automatically fetching the image preview when the image is large enough (and the page does not refresh).

**Comment by adriana-alter** [comment]
Weird.  I am now having other problems from pulling in the new version of `master` (stay tuned!), so maybe it's all part of the same thing...

**Comment by adriana-alter** [comment]
A fun example:

Screen Shot 2019-06-06 at 11 01 09 AM

So, here's the catch: there is no `Collapsible-test` file.  There is in fact no Collapsible.  That's the thing we replaced with the reusable Panel.  Months ago.  What gives?  (Is it a GHOST?)

**Comment by EdwinGuzman** [comment]
Delete your `lib` folder. The source was compiled correctly and that Collapsible component's tests passed but when it was removed the compiled code was probably still in the `lib` folder. Running the tests doesn't override that folder and instead just updates the compiled files. So now that you're updating this and the syntax changed for the tests, it's failing. This could be fixed with updating the test script to delete and recreate the `lib` folder.

**Comment by adriana-alter** [comment]
Ghost successfully exorcised; thank you!

**Comment by adriana-alter** [comment]
Note: this commit looks enormous because I pulled in the new version of `master`.  The only actual changes are in `BookCoverEditor` and `BookCoverEditor-test`.

**Comment by EdwinGuzman** [comment]
That's the loveliest portrait of a lion ever.

**Comment by adriana-alter** [comment]
🦁

**Comment by EdwinGuzman** [comment]
Looks fine. I will retest soon.

**Pull request merged**
