### PR TITLE
Use new Panel onEnter prop

### PR DESCRIPTION
**Pull request by adriana-alter**
Implementation of https://github.com/NYPL-Simplified/reusable-components/pull/10, which resolves https://jira.nypl.org/browse/SIMPLY-1882

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
I noticed that the panel now lost the smooth transition when opening and closing and now just opens and closes. Is this intended?

**Comment by adriana-alter** [comment]
The smooth transition was coming from react-bootstrap.  I think it's fine for the panel to just open and close.  (We can certainly consider replicating the react-bootstrap functionality by writing our own animation code--probably pretty easy via keyframes--but that's a conversation for another day!)

**Comment by EdwinGuzman** [comment]
Looks good but you need to actually import the new `1.3.2` version of the reusable-components package.

**Comment by adriana-alter** [comment]
Will do once `1.3.2` is published!

**Pull request merged**
