### PR TITLE
List page scroll

### PR DESCRIPTION
**Pull request by adriana-alter**
Resolves https://jira.nypl.org/browse/SIMPLY-2426 (footer on list manager page blocks content)

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
This seems fine overall but if you have 50 items in a list, then the page is very long. The scroll box before was to prevent that, so not sure if we should have a very long page or a longish box that scrolls with up to 50 items.

**Comment by adriana-alter** [comment]
I think the long page is okay.  (Especially if we're going to overhaul the list curation soon anyway...)

**Comment by EdwinGuzman** [comment]
That may not be any time soon though!

**Comment by adriana-alter** [comment]
True.  But the scroll box seems to be more trouble than it's worth.  Do you think it's actually a problem to have a long page, or...?

**Comment by EdwinGuzman** [comment]
I do think it's a problem to have a long page in this case because you may want to see the rest of the page while scrolling through the lists of book. So maybe you want to compare a book in one list with the other list. In that case you can't because there's no bounding box.

**Comment by adriana-alter** [comment]
Ah.  Fair.  I'll see what I can do!

**Pull request merged**
